version: "3"

services:
  postgresql:
    build: ./postgresql
    volumes: 
      - ./data/postgres:/var/lib/postgres
      - ./data/postgres-files:/var/lib/postgres-files/
    ports:
      - "5432:5432"
    environment:
        POSTGRES_DB: demo
        POSTGRES_USER: demo
        POSTGRES_PASSWORD: demo